# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugatestimulusresult',
            name='play_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='conjugatestimulusresult',
            name='response_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
