# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180208_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjugateResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DurationField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.ConjugateStimulusResultsBlock')),
            ],
        ),
        migrations.RemoveField(
            model_name='conjugatestimulusresult',
            name='response_number',
        ),
        migrations.AddField(
            model_name='conjugatestimulusresult',
            name='trial',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairedstimulusresult',
            name='trial',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stimulus',
            name='name',
            field=models.CharField(default='Elevensies', max_length=500),
            preserve_default=False,
        ),
    ]
